# Generated by Django 5.0.6 on 2024-05-09 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0004_alter_projects_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discription', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('Cdate', models.DateField(default=datetime.date.today)),
                ('Udate', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
