# Generated by Django 5.0.6 on 2024-05-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0006_taskdb_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdb',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
