# Generated by Django 5.0.6 on 2024-05-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0007_taskdb_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdb',
            old_name='Title',
            new_name='TitleT',
        ),
    ]
